Gracefully handle null tokens when encoding AuthResponse
datastax/native-protocol pull request #41
Opened 2021-10-11 19:04 UTC by akhaku

AuthResponse tokens come from ByteBuffer objects returned by
Authenticator methods. They may be null, and we used to
support null tokens until recently. This change restores
support for null AuthResponse tokens.

2021-10-26 23:16 UTC, akhaku commented
cc @adutra

2021-10-27 12:16 UTC, adutra requested changes
Thank you for putting this PR up!

2021-10-27 12:16 UTC, adutra commented on src/main/java/com/datastax/oss/protocol/internal/request/AuthResponse.java
> +      if (token != null) {
You still need to write the token if it is null:

```suggestion
      if (token == null) {
        encoder.writeBytes((ByteBuffer) null, dest);
      } else {
```

2021-10-27 22:25 UTC, akhaku commented on src/main/java/com/datastax/oss/protocol/internal/request/AuthResponse.java
> +      if (token != null) {
huh, okay, thanks

2021-10-29 12:48 UTC, adutra requested changes

2021-10-29 12:48 UTC, adutra commented on src/test/java/com/datastax/oss/protocol/internal/request/AuthResponseTest.java
> +  }
```suggestion

  @Test
  @UseDataProvider(location = TestDataProviders.class, value = "protocolV3OrAbove")
  public void should_encode_and_decode_null_token(int protocolVersion) {
    AuthResponse initial = new AuthResponse(null);
    int encodedSize = encodedSize(initial, protocolVersion);
    MockBinaryString encoded = encode(initial, protocolVersion);
    assertThat(encoded).isEqualTo(new MockBinaryString().bytes("0x"));
    assertThat(encodedSize).isEqualTo(PrimitiveSizes.INT);
    AuthResponse decoded = decode(encoded, protocolVersion);
    assertThat(Bytes.toHexString(decoded.token)).isEqualTo("0x");
  }
```

Thank you! I think you could improve your test, see my suggestion. But you will need to change `MockPrimitiveCodec` as well since this component cannot currently process null buffers:

```
  @Override
  public void writeBytes(ByteBuffer bytes, MockBinaryString dest) {
    if (bytes == null) {
      dest.bytes("0x");
    } else {
      dest.bytes(Bytes.toHexString(bytes));
    }
  }
```

2021-10-29 18:25 UTC, akhaku commented on src/test/java/com/datastax/oss/protocol/internal/request/AuthResponseTest.java
> +  }
Oh interesting, thanks will do.

2021-11-22 18:25 UTC, akhaku commented
Okay I think this is ready now, @adutra

2021-11-23 16:19 UTC, adutra approved these changes

2021-11-23 16:22 UTC, merged

2021-11-23 16:22 UTC, adutra commented
Thank you @akhaku !